@url = https://localhost:5001

### Create new product
POST {{url}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "tera jest ladnie",
    "description": "desc",
    "vendor": "vendor",
    "price": 1,
    "quantity": 1
}
