@url = https://localhost:5001


### CREATE new product
POST {{url}}/products
Content-Type: application/json

{
    "name": "super produkt",
    "description": "desc",
    "vendor": "vendor",
    "price": 1,
    "quantity": 1
}

### BROWSE products
GET {{url}}/products

### DELETE product
DELETE {{url}}/products/d9910038-80e4-4e03-bc22-5fd98ae674e1

