@url = https://localhost:5001
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZDhiZmE1ZWI1MjY0Zjk1OGQ4MGRhYTBlODQzMmExNSIsInVuaXF1ZV9uYW1lIjoiZmQ4YmZhNWViNTI2NGY5NThkODBkYWEwZTg0MzJhMTUiLCJqdGkiOiJkZWI4NDA4Yy1iMTIwLTQ0ZDEtYTc0Ni1lYWFhYzY5YTlkNzIiLCJpYXQiOiIxNTU0NzQ1Njk0ODY0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoidXNlciIsIm5iZiI6MTU1NDc0NTY5NCwiZXhwIjoxNTU0NzQ1NzU0LCJpc3MiOiJNeVNob3AifQ.0X9OjQvJTkLW5ZJxkWFhuvG-yoCbCQkNbrH6N-ovyIg
@refreshToken = AQAAAAEAACcQAAAAEG4cyi369kSpGEogMnwS/pv3TF3P3bWHZSadhkVazYJek477aP33TGqhiUM2tTsSDg==

### CREATE new product
POST {{url}}/products
Content-Type: application/json

{
    "name": "very new product",
    "description": "desc",
    "vendor": "vendor",
    "price": 1,
    "quantity": 1
}

### BROWSE products
GET {{url}}/products/
Authorization: Bearer {{token}}

@productId = d92c3532-d103-4666-9cfb-f05416063ea1

### GET product with specific id
GET {{url}}/products/{{productId}}


### UPDATE product with specific id
PUT {{url}}/products/{{productId}}
Content-Type: application/json

{
    "name": "Nowa nazwa",
    "description": "desc",
    "vendor": "vendor",
    "price": 1,
    "quantity": 1
}

### DELETE product
DELETE {{url}}/products/{{productId}}


### SIGN UP
POST {{url}}/identity/sign-up
Content-Type: application/json

{
    "email": "tomek.klag@gmail.com",
    "password": "secret"
}

### SIGN IN
POST {{url}}/identity/sign-in
Content-Type: application/json

{
    "email": "tomek.klag@gmail.com",
    "password": "secret"
}

### REFRESH TOKEN
POST {{url}}/access-token/refresh
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}